name: Deploy to GitHub Pages

on:
  push:
    branches:
      - '**'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  explain-non-default:
    if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch)
    runs-on: ubuntu-latest
    steps:
      - name: Skip notice
        env:
          DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
        run: |
          echo "This workflow only deploys the site when pushing to the ${DEFAULT_BRANCH} branch."
          echo "Current ref: ${GITHUB_REF_NAME}. Deployment has been skipped."

  deploy:
    if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
